Refactor deployment script to remove unnecessary flags and improve deployment process

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -18,7 +18,7 @@ jobs:
       DB_USERNAME: ${{ secrets.DB_USERNAME }}
       DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
-      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # Add Docker Username if needed
+      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
       GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
 
@@ -26,11 +26,11 @@ jobs:
       - name: 'Checkout repository'
         uses: actions/checkout@v2
 
-      - id: 'auth'
-        name: 'Authenticate to Google Cloud'
+      - name: 'Authenticate to Google Cloud'
+        id: 'auth'
         uses: 'google-github-actions/auth@v2'
         with:
-          credentials_json: '${{ env.GCP_SERVICE_ACCOUNT_KEY }}'
+          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' # Correctly pass JSON here
 
       - name: 'Set Google Cloud Project'
         run: gcloud config set project ${{ env.GCP_PROJECT_ID }}
@@ -38,11 +38,23 @@ jobs:
       - name: 'Log in to Docker Hub'
         uses: docker/login-action@v2
         with:
-          username: ${{ env.DOCKER_USERNAME }}
-          password: ${{ env.DOCKER_PASSWORD }}
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: 'Check if scripts directory exists'
+        run: |
+          if [ ! -d "scripts" ]; then
+            echo "scripts directory not found!"
+            exit 1
+          fi
 
       - name: 'Run deployment script'
         run: |
           cd scripts
-          chmod +x deploy.sh
-          ./deploy.sh
+          if [ -f "deploy.sh" ]; then
+            chmod +x deploy.sh
+            ./deploy.sh
+          else
+            echo "deploy.sh script not found!"
+            exit 1
+          fi
