Update deployment workflow to exclude the 'develop' branch and add scripts for deploying and setting environment variables

diff --git a/.github/workflows/deployment-workflow.yml b/.github/workflows/deployment-workflow.yml
--- a/.github/workflows/deployment-workflow.yml
+++ b/.github/workflows/deployment-workflow.yml
@@ -1,13 +1,13 @@
 name: Deployment Pipeline
+
 on:
   pull_request:
     branches:
-      - develop
       - main
+      - develop
 
 jobs:
   deploy:
-    name: Deploy
     runs-on: ubuntu-latest
     env:
       DB_URL: ${{ secrets.DB_URL }}
@@ -20,39 +20,70 @@ jobs:
       SPRINGBOOT_ENV: ${{ secrets.SPRINGBOOT_ENV }}
       RECOMMENDATIONS_ENV: ${{ secrets.RECOMMENDATIONS_ENV }}
       NOTIFICATIONS_ENV: ${{ secrets.NOTIFICATIONS_ENV }}
-      
+
     steps:
-      - name: Checkout repository
+      - name: 'Checkout repository'
         uses: actions/checkout@v2
-      - name: Authenticate to Google Cloud
-        id: auth
-        uses: google-github-actions/auth@v2
+
+      - name: 'Authenticate to Google Cloud'
+        id: 'auth'
+        uses: 'google-github-actions/auth@v2'
         with:
-          credentials_json: ${{ env.GCP_SERVICE_ACCOUNT_KEY }}
-      - name: Set Google Cloud Project
+          credentials_json: '${{ env.GCP_SERVICE_ACCOUNT_KEY }}' # Correctly pass JSON here
+
+      - name: 'Set Google Cloud Project'
         run: gcloud config set project ${{ env.GCP_PROJECT_ID }}
-      - name: Log in to Docker Hub
+
+      - name: 'Log in to Docker Hub'
         uses: docker/login-action@v2
         with:
           username: ${{ env.DOCKER_USERNAME }}
           password: ${{ env.DOCKER_PASSWORD }}
-      - name: Docker Auth
+      
+      - name: 'Docker Auth'
         run: |
           gcloud auth configure-docker "us-east1-docker.pkg.dev"
+      
       - name: Install Flutter
         uses: subosito/flutter-action@v2
         with:
-          flutter-version: 3.22.1
-      - name: Check for changes in services
-        run: ./scripts/check_changes.sh
-      - name: Create and write environment variables to .env files
-        run: ./scripts/set_env_files.sh
-      - name: Deploy services with changes
-        run: ./scripts/deploy_services.sh
-      - name: Delete the .env files
+          flutter-version: '3.22.1'
+    
+      - name: Install dependencies for Frontend
+        working-directory: ./src/Frontend
+        run: flutter pub get
+
+      - name: 'Create and write environment variables to .env files'
+        run: |
+          echo "${{ env.SPRINGBOOT_ENV }}" > src/Backend/.env
+          echo "${{ env.SPRINGBOOT_ENV }}" > src/Analytics/.env
+          echo "${{ env.RECOMMENDATIONS_ENV }}" > src/recommendation-service/.env
+          echo "${{ env.NOTIFICATIONS_ENV }}" > src/notification-service/.env
+          echo "${{ env.NOTIFICATIONS_ENV }}" > src/storage-service/.env
+
+      - name: 'Run deployment script'
+        run: |
+          cd scripts
+          if [ -f "./check-changes.sh" ]; then
+            chmod +x ./check-changes.sh
+            ./check-changes.sh
+          else
+            echo "./check-changes.sh script not found!"
+            exit 1
+          fi
+          if [ -f "./deploy_services.sh" ]; then
+            chmod +x ./deploy_services.sh
+            ./deploy_services.sh
+          else
+            echo "./deploy_services.sh script not found!"
+            exit 1
+          fi
+
+      - name: 'Delete the .env files'
         run: |
           rm -f src/Backend/.env
           rm -f src/Analytics/.env
           rm -f src/recommendation-service/.env
           rm -f src/notification-service/.env
           rm -f src/storage-service/.env
+
